apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vox-itsm

resources:
  - ../kubernetes
  - dependencies.yaml
  - secret.yaml
  - network-policy.yaml

images:
  - name: vox-itsm-backend
    newTag: rehearsal
  - name: vox-itsm-frontend
    newTag: rehearsal

patches:
  - path: config-patch.yaml
