import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bell, BookOpen, Bot, Boxes, ChevronDown, CircleHelp, ClipboardList, Clock3, Command, FilePlus2, Gauge, Grid2X2, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Sparkles, TicketCheck, UserRound, X } from 'lucide-react';
import { messages, type Locale } from './i18n/messages';
import './styles.css';

type Item = { id:string; title:string; titleEn:string; type:string; typeEn:string; priority:'Критический'|'Высокий'|'Средний'; assignee:string; sla:string; updated:string; avatar:string };
const items:Item[]=[
 {id:'INC-1842',title:'Недоступен VPN для удалённых сотрудников',titleEn:'VPN unavailable for remote employees',type:'Инцидент',typeEn:'Incident',priority:'Критический',assignee:'Алексей К.',sla:'00:42',updated:'8 мин',avatar:'АК'},
 {id:'REQ-9217',title:'Доступ к финансовой витрине данных',titleEn:'Access to the financial data mart',type:'Запрос',typeEn:'Request',priority:'Высокий',assignee:'Мария В.',sla:'03:15',updated:'21 мин',avatar:'МВ'},
 {id:'INC-1838',title:'Ошибка синхронизации корпоративной почты',titleEn:'Corporate mail synchronization error',type:'Инцидент',typeEn:'Incident',priority:'Высокий',assignee:'Вы',sla:'04:48',updated:'34 мин',avatar:'АЯ'},
 {id:'CHG-422',title:'Обновление кластеров PostgreSQL',titleEn:'PostgreSQL cluster upgrade',type:'Изменение',typeEn:'Change',priority:'Средний',assignee:'Дмитрий С.',sla:'Завтра',updated:'1 ч',avatar:'ДС'}];
function App(){
 const [locale,setLocale]=useState<Locale>(()=>(localStorage.getItem('vox-locale') as Locale)||'ru'); const [nav,setNav]=useState('overview'); const [menu,setMenu]=useState(false); const [query,setQuery]=useState(''); const [create,setCreate]=useState(false);
 const t=messages[locale]; useEffect(()=>{ document.documentElement.lang=locale; localStorage.setItem('vox-locale',locale)},[locale]);
 const visible=useMemo(()=>items.filter(x=>`${x.id} ${locale==='ru'?x.title:x.titleEn}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const navItems=[['overview',LayoutDashboard,t.overview],['my',TicketCheck,t.myWork],['queues',Grid2X2,t.queues],['catalog',ClipboardList,t.catalog],['knowledge',BookOpen,t.knowledge],['cmdb',Boxes,t.cmdb]] as const;
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><span className="brand-mark"><span></span><span></span><span></span></span><b>vox</b><em>ITSM</em></div><div className="workspace"><span className="workspace-icon">N</span><div><strong>Northstar</strong><small>{t.workspace}</small></div><ChevronDown size={15}/></div><nav>{navItems.map(([key,Icon,label])=><button key={key} className={nav===key?'active':''} onClick={()=>setNav(key)}><Icon size={18}/><span>{label}</span>{key==='my'&&<i>12</i>}</button>)}</nav><div className="nav-label">УПРАВЛЕНИЕ</div><nav><button><Gauge size={18}/><span>{t.reports}</span></button><button><Settings size={18}/><span>{t.settings}</span></button></nav><div className="sidebar-bottom"><div className="security"><ShieldCheck size={16}/><span>Защищённое соединение</span></div><button className="profile"><span className="avatar me">АЯ</span><span><b>Анна Яковлева</b><small>Service desk</small></span><MoreHorizontal size={17}/></button></div></aside>
  <main><header><button className="mobile-menu"><Menu/></button><div className="crumb"><span>Northstar</span><b>/</b><strong>{t.overview}</strong></div><div className="header-actions"><label className="search"><Search size={18}/><input aria-label={t.search} placeholder={t.search} value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label><button className="icon-button" aria-label="Notifications"><Bell size={19}/><span className="dot"></span></button><div className="language"><button onClick={()=>setMenu(!menu)} aria-expanded={menu}><span>RU</span><ChevronDown size={14}/></button>{menu&&<div className="language-menu"><p>{t.language}</p><button className={locale==='ru'?'selected':''} onClick={()=>{setLocale('ru');setMenu(false)}}>{t.russian}<span>RU</span></button><button className={locale==='en'?'selected':''} onClick={()=>{setLocale('en');setMenu(false)}}>{t.english}<span>EN</span></button></div>}</div></div></header>
  <section className="content"><div className="headline"><div><p className="eyebrow">{locale==='ru'?'30 ИЮЛЯ · СРЕДА':'JULY 30 · WEDNESDAY'}</p><h1>{t.greeting} <span>✦</span></h1><p>{t.subtitle}</p></div><button className="primary" onClick={()=>setCreate(!create)}><Plus size={18}/>{t.create}</button>{create&&<div className="create-popover"><button><span className="create-icon incident"><CircleHelp/></span><span><b>{t.newIncident}</b><small>Сообщить о неполадке</small></span></button><button><span className="create-icon request"><FilePlus2/></span><span><b>{t.newRequest}</b><small>Заказать услугу</small></span></button></div>}</div>
  <div className="metrics"><Metric icon={<TicketCheck/>} color="violet" value="24" label={t.open} detail={locale==='ru'?'+5 за неделю':'+5 this week'}/><Metric icon={<Clock3/>} color="amber" value="6" label={t.due} detail={locale==='ru'?'2 менее чем за час':'2 in under an hour'}/><Metric icon={<Bell/>} color="rose" value="2" label={t.breached} detail={locale==='ru'?'Нужно внимание':'Needs attention'}/><Metric icon={<Sparkles/>} color="mint" value="96%" label={t.satisfaction} detail={locale==='ru'?'За последние 30 дней':'Last 30 days'}/></div>
  <div className="dashboard-grid"><section className="panel queue"><div className="panel-header"><div><h2>{t.workQueue}</h2><p>{locale==='ru'?'Показано 8 из 24 обращений':'Showing 8 of 24 requests'}</p></div><button className="text-button">{t.viewAll} <span>→</span></button></div><div className="table"><div className="table-head"><span>{locale==='ru'?'ОБРАЩЕНИЕ':'REQUEST'}</span><span>{t.priority}</span><span>{t.assignee}</span><span>{t.target}</span><span>{t.updated}</span></div>{visible.map(i=><div className="row" key={i.id}><div className="ticket"><b>{i.id}</b><span>{locale==='ru'?i.title:i.titleEn}</span><small>{locale==='ru'?i.type:i.typeEn}</small></div><span className={'priority '+(i.priority==='Критический'?'critical':i.priority==='Высокий'?'high':'medium')}><i></i>{locale==='ru'?i.priority:(i.priority==='Критический'?'Critical':i.priority==='Высокий'?'High':'Medium')}</span><div className="person"><span className="avatar">{i.avatar}</span><span>{i.assignee}</span></div><span className={i.sla==='00:42'?'sla urgent':'sla'}>{i.sla}</span><span className="muted">{i.updated}</span></div>)}{visible.length===0&&<div className="empty">{locale==='ru'?'Ничего не найдено. Попробуйте изменить запрос.':'No results found. Try a different search.'}</div>}</div></section>
  <aside className="right-rail"><section className="panel flow"><div className="panel-header"><div><h2>{t.flow}</h2><p>{locale==='ru'?'Текущая нагрузка':'Current workload'}</p></div><MoreHorizontal size={19}/></div><div className="donut"><div><b>24</b><span>{locale==='ru'?'активных':'active'}</span></div></div><div className="legend"><p><i className="l1"></i>{locale==='ru'?'Новые':'New'} <b>8</b></p><p><i className="l2"></i>{locale==='ru'?'В работе':'In progress'} <b>11</b></p><p><i className="l3"></i>{locale==='ru'?'Ожидают':'Waiting'} <b>5</b></p></div></section><section className="copilot"><div className="copilot-top"><span className="bot"><Bot size={19}/></span><div><h2>{t.assistant}</h2><span><i></i> онлайн</span></div><button><MoreHorizontal size={18}/></button></div><p>{t.assistantText}</p><div className="suggestions"><button>{locale==='ru'?'Что горит сейчас?':'What is urgent?'}</button><button>{locale==='ru'?'Сводка по SLA':'SLA summary'}</button></div><label><input placeholder={t.ask}/><Command size={16}/></label></section></aside></div></section></main></div> }
function Metric({icon,color,value,label,detail}:{icon:React.ReactNode;color:string;value:string;label:string;detail:string}){return <article className="metric"><span className={'metric-icon '+color}>{icon}</span><div><span className="metric-label">{label}</span><b>{value}</b><small>{detail}</small></div></article>};
createRoot(document.getElementById('root')!).render(<App/>);
