springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  structured:
    format:
      console: ecs
  include-application-name: false

management:
  endpoint:
    health:
      show-details: never
