apiVersion: v1
kind: Secret
metadata:
  name: itsm-secrets
  namespace: vox-itsm
type: Opaque
stringData:
  DATABASE_URL: REPLACE_ME
  DATABASE_USER: REPLACE_ME
  DATABASE_PASSWORD: REPLACE_ME
  RABBITMQ_USER: REPLACE_ME
  RABBITMQ_PASSWORD: REPLACE_ME
  REDIS_PASSWORD: REPLACE_ME
  S3_ACCESS_KEY: REPLACE_ME
  S3_SECRET_KEY: REPLACE_ME
  OIDC_ISSUER_URI: https://id.example.com/realms/itsm
